import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: '核心概念',
      link: {
        type: 'generated-index',
        slug: '/concepts',
        description: 'Axiom Agent 的核心概念与术语。',
      },
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'category',
      label: '系统架构',
      link: {
        type: 'generated-index',
        slug: '/architecture',
        description: 'Axiom Agent 的系统架构与模块设计。',
      },
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: '技术研究',
      link: {
        type: 'generated-index',
        slug: '/research',
        description: 'Axiom Agent 相关技术调研与实验结论。',
      },
      items: [{type: 'autogenerated', dirName: 'research'}],
    },
    {
      type: 'category',
      label: '架构决策',
      link: {
        type: 'generated-index',
        slug: '/decisions',
        description: 'Axiom Agent 的架构决策记录。',
      },
      items: [{type: 'autogenerated', dirName: 'decisions'}],
    },
  ],
};

export default sidebars;
